
# change this to whatever app name
# you set up on Google App Engine
application: jsonp-db-redux

version: 1
api_version: 1
runtime: python27
threadsafe: false

libraries:
- name: django
  version: "1.2"

handlers:
- url: /index.html
  static_files: index.html
  upload: index.html

# this one is an admin login
# strip this URL paragraph for no auto cleanup
- url: /cleanAll
  script: jsonpdb.py
  login: admin

# needed for the specific icons and styles
# of the demo page
- url: /icons-and-styles
  static_dir: icons-and-styles

# needed for the specific js libs
# of the demo page
- url: /jslibs
  static_dir: jslibs

# only needed for the images in the doc
- url: /images
  static_dir: images

- url: /.*
  script: jsonpdb.py
