application: jsonp-db-redux
version: 1
api_version: 1
runtime: python27
threadsafe: false

libraries:
- name: django
  version: "1.2"

handlers:
- url: /index.html
  static_files: index.html
  upload: index.html

# this one is an admin login
- url: /cleanAll
  script: jsonpdb.py
  login: admin

- url: /.*
  script: jsonpdb.py
